apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-remediation-secrets
  namespace: ai-remediation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-backend
    kind: ClusterSecretStore
  target:
    name: ai-remediation-secrets
    creationPolicy: Owner
  data:
    - secretKey: OVH_AI_ENDPOINTS_ACCESS_TOKEN
      remoteRef:
        key: ai-remediation-source
        property: OVH_AI_ENDPOINTS_ACCESS_TOKEN
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: ai-remediation-source
        property: GITHUB_TOKEN
