apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-web
  namespace: demo-vulnerable
  labels:
    app: vulnerable-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-web
  template:
    metadata:
      labels:
        app: vulnerable-web
    spec:
      serviceAccountName: dvwa-sa
      automountServiceAccountToken: false
      containers:
        - name: dvwa
          image: myregistry.example.com/vulnerables/web-dvwa:1.2.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password