apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-web
  namespace: demo-vulnerable
  labels:
    app: vulnerable-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-web
  template:
    metadata:
      labels:
        app: vulnerable-web
    spec:
      hostNetwork: false
      serviceAccountName: dvwa-sa
      automountServiceAccountToken: true
      containers:
        - name: dvwa
          image: vulnerables/web-dvwa:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAIOSFODNN7EXAMPLE"
            - name: AWS_SECRET_ACCESS_KEY
              value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          volumeMounts:
            - name: host-root
              mountPath: /host
            - name: leaked-kubeconfig
              mountPath: /root/.kube
              readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: leaked-kubeconfig
          secret:
            secretName: leaked-kubeconfig
            items:
              - key: config
                path: config
