apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-nginx
  namespace: demo-vulnerable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-nginx
  template:
    metadata:
      labels:
        app: vulnerable-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0