apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alnoria
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: acc
          - env: prod
  template:
    metadata:
      name: "alnoria-{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Cyril62880/hackathon-equipe-15.git
        targetRevision: main
        path: "manifest/alnoria/overlays/{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{env}}-alnoria"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
