apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alnoria-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cyril62880/hackathon-equipe-15.git
    targetRevision: main
    path: manifest/alnoria/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-alnoria
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: alnoria-db
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
        - /spec/template/spec/dnsPolicy
        - /spec/template/spec/restartPolicy
        - /spec/template/spec/schedulerName
        - /spec/template/spec/securityContext
        - /spec/template/spec/terminationGracePeriodSeconds
        - /spec/updateStrategy
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/spec/volumeMode
        - /spec/volumeClaimTemplates/0/status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
