apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      releaseName: prometheus
      values: |
        grafana:
          enabled: true
          adminPassword: hackathon
          defaultDashboardsEnabled: true
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: monitoring
              label: grafana_dashboard
              labelValue: "1"
              folderAnnotation: grafana_folder
            datasources:
              enabled: true
              defaultDatasourceEnabled: true
              uid: prometheus

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false

        alertmanager:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
